spring:
  datasource:
    url: jdbc:mysql://192.168.10.10:3306/hades-dev?useUnicode=true&characterEncoding=utf-8
    username: hades
    password: hades
    driver-class-name: com.mysql.jdbc.Driver
#    type: org.apache.commons.dbcp2.BasicDataSource
  aop:
    auto: true

server:
  port: 80888

role:
  nfq:
    - 1
    - 2
  customer:
    - 1
    - 2
    - 3
  user:
    - name: haha
      id: 123
    - name: xixi
      id: 12222
